services:
  web:
    build:
      context: .
    container_name: django-waf
    working_dir: /app
    command: gunicorn waf.wsgi:application --bind 0.0.0.0:8000
    expose:
      - "8000"
    volumes:
      - ./waf:/app
    env_file: 
      - .env
  nginx-waf:
    image: owasp/modsecurity-crs:nginx
    container_name: nginx-waf
    ports:
      - "80:8080"
    environment:
      BACKEND: http://web:8000
      SERVER_NAME: localhost      
      CORS_HEADER_403_CONTENT_TYPE: "text/html"

      BLOCKING_PARANOIA: 3

      MODSEC_AUDIT_ENGINE: On
      MODSEC_AUDIT_LOG_FORMAT: Native
      MODSEC_AUDIT_LOG: /var/log/modsecurity/audit.log
      MODSEC_AUDIT_LOG_PARTS: ABCEFHZ

    volumes:
      - ./logs/modsecurity:/var/log/modsecurity
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - web

